Add some component
subroh0508/kotlin-material-ui pull request #40
Opened 2020-11-25 14:32 UTC by hamed-sb

Add
   +AutoComplete component
   +useAutoComplete hooks function
   +StylesProvider componen for support jss
   +some missing props

edit StyleBiulder for support static style

2020-12-19 11:37 UTC, subroh0508 requested changes
Sorry for the late review!

I tried to check the operation, but I got an error with the following code 😭  If it works in your local environment, I would like to see the sample code.

```kotlin
val data: Array<Data> = arrayOf(
    jsObject { name = "Mizuki Makabe"; age = 17 },
    jsObject { name = "Madoka Higuchi"; age = 17 },
)

autoComplete<Data> {
    attrs.options = data
    attrs.getOptionLabel = { it.name }
    attrs.renderInput = {
        buildElements {
            textField {
                console.log(Object.assign(attrs, it))
                Object.assign(attrs, it)
                attrs.label { +"Combo box" }
                attrs.variant = FormControlVariant.outlined
            }
        }
    }
}
```

Clicking on it will result in an error like this.
```
Uncaught TypeError: Cannot read property 'focus' of null
    at handleClick (webpack-internal:///../../node_modules/@material-ui/lab/esm/useAutocomplete/useAutocomplete.js:928)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:237)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:306)
    at executeDispatch (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:389)
    at executeDispatchesInOrder (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:411)
    at executeDispatchesAndRelease (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3278)
    at executeDispatchesAndReleaseTopLevel (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3287)
    at forEachAccumulated (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3259)
```

2020-12-25 16:48 UTC, hamed-sb commented
you must use props() method for set props
like this props( it as TextFieldProps)

sorry my English is not  good
thank for review

2021-02-21 16:50 UTC, subroh0508 commented on sample/src/main/kotlin/demo/components/InputAdornmentsDemo.kt
> +)
👍 👍 👍

2021-02-21 16:54 UTC, subroh0508 approved these changes
I think it's very good! I'm sorry I left it for two months 😭 
![madoka](https://user-images.githubusercontent.com/8080435/108632178-e7fb3c00-74b0-11eb-9054-980f5cef6500.jpg)

2021-02-21 16:54 UTC, merged